# general settings
name: 01_MSD_CSD
# name: debug_FeMaSR
model_type: FeMaSRModel 
scale: &upscale 1
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: CSD
    type: PairedImageDataset
    dataroot_gt: "../Dataset/CSD/Train/Gt"
    dataroot_lq: "../Dataset/CSD/Train/Snow"
    dataroot_lq_mask: "../Dataset/CSD/Train/Mask"
    io_backend:
      type: disk

    gt_size: 256
    use_resize_crop: True
    use_flip: True
    use_rot: True

    # data loader
    use_shuffle: true
    geometric_augs: True
    batch_size_per_gpu: &bsz 1
    num_worker_per_gpu: *bsz 
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: *bsz


  val:
    name: CSD
    type: PairedImageDataset
    dataroot_gt: "../Dataset/CSD/Test/Gt"  # 改为验证集路径
    dataroot_lq: "../Dataset/CSD/Test/Snow"
    dataroot_lq_mask: "../Dataset/CSD/Test/Mask"
    gt_size: 256
    io_backend:        
      type: disk 
    geometric_augs: false  # 验证时不需要数据增强


# network structures
network_g:
  type: MSDeformableNAIR
  inp_channels: 3
  out_channels: 3
  dim: 36  # 基础特征维度
  num_blocks: [4, 6, 6, 8]  # 每个阶段的块数
  kernel_size: [3, 3, 3, 3]  # 卷积核大小
  dilation: [1, 1, 1, 1]  # 膨胀率
  heads: [6, 6, 12, 12]  # 能被3整除的注意力头数
  num_refinement_blocks: 4
  ffn_expansion_factor: 2
  bias: false
  LayerNorm_type: 'WithBias'
  rel_pos_bias: true
  dual_pixel_task: false
  global_residual: true



# path
path:
  pretrain_network_hq: ~
  pretrain_network_g: ~
  pretrain_network_d: ~
  strict_load: false
  resume_state: ~


train:
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000, 250000]
    gamma: !!float 0.5    # 确保是float类型

  total_iter: 300000
  warmup_iter: 1000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
    
  pixel_ssim_opt:
    type: SSIMLoss
    loss_weight: 0.2
    
  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    
  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 0.1

# validation settings
val:
  val_freq: !!float 5000
  save_img: true

  key_metric: psnr
  metrics:
    psnr:
      type: psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: ssim
      crop_border: 0
      test_y_channel: false
    lpips:
      type: lpips
      better: lower

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 10000
  save_latest_freq: !!float 5000
  show_tf_imgs_freq: !!float 2000
  use_tb_logger: true

dist_params:
  backend: nccl
  port: 16500
find_unused_parameters: true
